### ISSUE TITLE
Define some game modes

### ISSUE THREAD

**Issue by Sudobeast** [DaDragonDen/pause-game#14]
# Flagpole Mode
Get to the end of the level to win!

## Other clear conditions
The flagpole might be inaccessible until the player meets some conditions like:
* Win while the game is paused.
* Win while the game is unpaused.
* Win the game with a certain amount of time.

**Comment by Sudobeast** [comment]
@nazthesilly do you think there should be any other level modes?

**Comment by nazthesilly** [comment]
to be completely honest i dont think we have enough time before the deadline to add another mode and should just focus on the main game 4 now. if we wanted to we could always go back and add more to the game after submission but I think we shouldn't broaden the scope of the game too much

**Comment by Sudobeast** [comment]
sounds good to me 😎
